apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: example-ptpconfig
spec:
  profile:
  - name: "profile1"
    interface: "ens2f1"
    ptp4lOpts: "-s -2"
    phc2sysOpts: "-a -r"
    ptpClockThreshold: {}
  recommend:
  - profile: "profile1"
    priority: 4
    match:
    - nodeName: "voereir02"
      nodeLabel: "kubernetes.io/hostname="
