apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: ptp-master
  namespace: node-feature-discovery
spec:
  nodeSelector:
    matchLabels:
      ptp-role: "master"

  ptpSettings:
    - name: master-profile
      iface: ens2f1
      ptp4lOpts:
        - "-2"               # PTPv2
        - "-s"               # Slave-only off → this becomes master
        - "-m"               # Logging to stdout
        - "-f /etc/ptp4l.conf"
      phc2sysOpts:
        - "-a"               # Automatic clock synchronization
        - "-r"               # Step hardware clock
        - "-n 24"            # Sync interval
